wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=dbpassword
    ports:
     - "127.0.0.1:8000:80"
    volumes:
     - ./code:/code
     - ./html:/var/www/html
mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=rootpassword
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql